version: '3.8'

services:
  # Container do Banco de Dados
  db:
    image: postgres:14-alpine
    container_name: smou_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_aro
    ports:
      - "5433:5432" # Mantém a porta exposta caso você queira acessar via DBeaver/PgAdmin externamente
    volumes:
      - postgres_data:/var/lib/postgresql/data # Salva os dados permanentemente no servidor

  # Container da Aplicação Flask
  web:
    build: .
    container_name: smou_web
    restart: always
    ports:
      - "5001:5000" # Mapeia a porta 80 do servidor (padrão web) para a 5000 do Flask
    depends_on:
      - db
  #environment:
  #  - SECRET_KEY=sua_chave_secreta_aqui

# Cria um volume permanente para o PostgreSQL não perder dados ao reiniciar
volumes:
  postgres_data: